title: 'go deploy - Azure Case Studies'
remote_theme: godeploy/Jekyll-Theme
exclude:
  - readme.md
  - .github/
header_pages:
  - index.html
author: go deploy - Online Labs
twitter_username: godeployit
github_username:  godeploy
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
